name: Check site validity

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download gutenberg
        run: >
          curl -L
          https://github.com/getzola/zola/releases/download/v0.12.0/zola-v0.12.0-x86_64-unknown-linux-gnu.tar.gz
          | sudo tar -C /usr/local/bin -xzf -
      - run: zola build
